### PR TITLE
(yegor256/cactoos#1531) Bump cactoos to 0.49

### PR DESCRIPTION
**Pull request by victornoel**
For yegor256/cactoos#1531

### CODE REVIEW

**Comment by victornoel** [comment]
@rultor merge

**Comment by victornoel** [comment]
@rultor release, tag is `0.23`

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @victornoel[/z](https://www.0crat.com/u/victornoel) please review this and merge or reject

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#222` is not assigned, can't get performer

**Pull request merged**
