### PR TITLE
(#213) Consistant naming of matcher objects

### PR DESCRIPTION
**Pull request by baudoliver7**
#213

- Rename `TextIs` to `IsText`
- Rename `NumberIs` to `IsNumberText`
- Rename `InputHasContent` to `HasContent`
- Rename `TextHasString` to `HasString`
- Rename `ScalarHasValue` to `HasValue`
- Rename `FuncApplies` to `IsApplicable`

### CODE REVIEW

**Comment by baudoliver7** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/217#issuecomment-758494830))

@baudoliver7 This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#217](https://github.com/llorllale/cactoos-matchers/issues/217) is [in scope](http://www.zerocracy.com/policy.html#14) for 8hr
  * The role is `REV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [7hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @baudoliver7[/z](https://www.0crat.com/u/baudoliver7): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23217%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/217#issuecomment-760246932))

@victornoel The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#217](https://github.com/llorllale/cactoos-matchers/issues/217), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#217](https://github.com/llorllale/cactoos-matchers/issues/217); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by victornoel** [comment]
@baudoliver7 unfortunately now there are conflicts because we merged another PR :)

**Comment by baudoliver7** [comment]
@victornoel No conflit now.

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#217` is not assigned, can't get performer

**Pull request merged**
