### PR TITLE
(#148) Remove usage of deprecated CollectionOf

### PR DESCRIPTION
**Pull request by victornoel**
This is for #148.

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#151](https://github.com/llorllale/cactoos-matchers/issues/151); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by victornoel** [comment]
@paulodamaso ping

**Comment by 0crat** [comment]
This pull request [#151](https://github.com/llorllale/cactoos-matchers/issues/151) is assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C63314D6Z/42340dec-cce0-4b9d-850e-22e9fc26baff); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by victornoel** [comment]
@marceloamadeu can I get a review here?

**Comment by marceloamadeu** [comment]
@victornoel Some checks were not successful. Is it necessary to correct?

**Comment by victornoel** [comment]
@marceloamadeu I don't know, I don't think the codecov checks are problematic and I don't know why the CI didn't finish.

@paulodamaso can you re-run the CI maybe?

**Comment by paulodamaso** [comment]
@victornoel I can't, I don't have the access to do it on llorlalle/cactoos-matchers (?)
image
Can you try to push it again?

**Comment by victornoel** [comment]
@paulodamaso I've pushed again but nothing seem to happens... I think there is a configuration problem with travis maybe...

**Comment by paulodamaso** [comment]
@llorllale Can you try to trigger this travis build manually?

**Comment by llorllale** [comment]
@paulodamaso done: https://travis-ci.org/github/llorllale/cactoos-matchers/builds/673077793

**Comment by paulodamaso** [comment]
@llorllale Thanks!

**Comment by paulodamaso** [comment]
@marceloamadeu Please go on with the review

**Comment by marceloamadeu** [comment]
@paulodamaso Good to merge.

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by victornoel** [comment]
@paulodamaso I think that the rultor integration is broken, the error doesn't seem to be related to this PR.

**Comment by victornoel** [comment]
@paulodamaso I opened an issue for rultor configuration problem: #152

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by victornoel** [comment]
@paulodamaso let me do something so that the PR passes all the checks

**Comment by victornoel** [comment]
@paulodamaso now it's ok, I added a test :)

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@victornoel Looks like #152 is fixed, could you please close it?

**Comment by 0crat** [comment]
Job [#151](https://github.com/llorllale/cactoos-matchers/issues/151) is not in the agenda of @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (13 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
Job [#151](https://github.com/llorllale/cactoos-matchers/issues/151) is not in the agenda of @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), can't set title

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
