### PR TITLE
(#99) Expand the scope of forbidden APIs

### PR DESCRIPTION
**Pull request by victornoel**
#99: there already was no usage of static methods, so I cleaned up things a bit:
- Forbid any use of Assert, Matchers and MatcherAssert
- Remove duplicates rules

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#101](https://github.com/llorllale/cactoos-matchers/issues/101) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#101](https://github.com/llorllale/cactoos-matchers/issues/101) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/8b43d4a0-aa78-4e0b-9a36-7921ef71bc28); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by victornoel** [comment]
@llorllale REV seems not be responding, anyway to get someone else or a review? :)

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/101#issuecomment-466705307))

@llorllale The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#101](https://github.com/llorllale/cactoos-matchers/issues/101), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#101](https://github.com/llorllale/cactoos-matchers/issues/101) is assigned to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr), here is [why](https://www.0crat.com/footprint/C63314D6Z/81d3fb33-a93f-416b-a849-76f2fb87670f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by Iprogrammerr** [comment]
@victornoel  There is not much to be added here, @llorllale good to merge.

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
The job [#101](https://github.com/llorllale/cactoos-matchers/issues/101) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Pull request merged**
