### PR TITLE
Upgrade to qulice 0.17.3

### PR DESCRIPTION
**Pull request by jsoroka**
For #10

This upgrades qulice to 0.17.3 and fixes the resultant errors: it removes the newly prohibited @version @author tags and changes the opening comment for each licence header.  Also removed checkstyle exclusion on resources folder, which does not break the build.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#21](https://github.com/llorllale/cactoos-matchers/issues/21) is assigned to @vssekorin[/z](https://www.0crat.com/u/vssekorin), here is [why](https://www.0crat.com/footprint/C63314D6Z/1801827103); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vssekorin[/z](https://www.0crat.com/u/vssekorin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#21](https://github.com/llorllale/cactoos-matchers/issues/21) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by elenavolokhova** [comment]
@VsSekorin According to our Policy;
> The code reviewer found at least three problems in the code

There were no issues found during this review. Please, confirm that you will try to find at least three issues next time.

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
