### PR TITLE
(#141) Fix travis build: error installing openjdk8

### PR DESCRIPTION
**Pull request by llorllale**
For #141

### CODE REVIEW

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#142` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
