### PR TITLE
(#83) Run on various Java version + latest codecov-action

### PR DESCRIPTION
**Pull request by victornoel**
Run on various Java version + latest codecov-action

### CODE REVIEW

**Comment by victornoel** [comment]
@llorllale could it be possible to change the project configuration to match with this new CI workflow? It seems the two "Tests (macOS-10.15)" and "Tests (ubuntu-18.04)" required checks are not the correct ones :)

**Comment by llorllale** [comment]
@victornoel done

**Comment by victornoel** [comment]
@llorllale thx a lot :)

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
