### PR TITLE
(#202) Fix bug and enable maven-shade-plugin

### PR DESCRIPTION
**Pull request by baudoliver7**
#202

- Fix bug
- Enable plugin

### CODE REVIEW

**Comment by victornoel** [comment]
@baudoliver7 thx, it seems to be working as expected after a few tests. Have you validated that all the matchers available only publicly (in their generics and in their public constructors) refer to the interfaces and not to the implementations?

It would be cool to enforce this at compile time, but I'm not sure how, maybe there are maven plugins for that?

**Comment by baudoliver7** [comment]
@victornoel please, let me have a look at this

**Comment by victornoel** [comment]
@baudoliver7 great, even if you just end up with some ideas, we can already create a todo in this PR :)

**Comment by baudoliver7** [comment]
@victornoel Ok

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#226](https://github.com/llorllale/cactoos-matchers/issues/226); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#226](https://github.com/llorllale/cactoos-matchers/issues/226); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by victornoel** [comment]
@baudoliver7 I will merge this and you can create another MR if we want to add todos and we can discuss ideas for the next steps in the ticket :)

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#226` is not assigned, can't get performer

**Pull request merged**
