### PR TITLE
#1 Coverage is too low

### PR DESCRIPTION
**Pull request by SharplEr**
For #1 
**Problem**
Codecov was too low and jococo checks failed.

**Solution**
Add some base tests.
Also, fix a problem with wrong package names in tests (which effect codecov).

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#15](https://github.com/llorllale/cactoos-matchers/issues/15) is now in scope, role is `REV`

**Comment by llorllale** [comment]
@SharplEr thanks - my bad for not realizing the wrong packages were being referenced.

Please fix all new `@since` tags - they should be set to `1.0`

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#15](https://github.com/llorllale/cactoos-matchers/issues/15) is now out of scope

**Pull request merged**
