### PR TITLE
(#165) Introduce Verifies to replace one-argument MatcherOf

### PR DESCRIPTION
**Pull request by victornoel**
This is in the continuation of #165 because sometimes it's required to write assertions with just a predicate

### CODE REVIEW

**Comment by victornoel** [comment]
@baudoliver7 thx for the comment. Btw I don't know why but they do not appear in the PR, only on the commit itself, I think maybe it's because you didn't add them via the "Files changed" tab of the PR.

**Comment by baudoliver7** [comment]
@victornoel Please, let me do it again.

**Comment by baudoliver7** [comment]
@victornoel You already did changes. Looks good for me :)

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by sereshqua** [comment]
@baudoliver7 please make sure you will find at least 3 issues during next CR, thanks!

**Pull request merged**
