### PR TITLE
#52: Replace all uses of MatcherAssert.assertThat(), part 1

### PR DESCRIPTION
**Pull request by dgroup**
This PR for #52 contains following changes:
 - 1 todo for activation of `de.thetaphi:forbiddenapis` plugin in order to restrict the usage of `MatchersAssert`, `Matchers`
 - 1 todo for the second part of the changes related to the #52 as it's huge
 - For 10 files with tests, the MatcherAsssert was `replaced` in favor of `Assertion`

### CODE REVIEW

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) everybody who has role `REV` is banned at [#70](https://github.com/llorllale/cactoos-matchers/issues/70); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by dgroup** [comment]
@llorllale the PR is ready for review

**Comment by dgroup** [comment]
@llorllale, @fabriciofx the PR is ready for review.

**Comment by llorllale** [comment]
@fabriciofx ping

**Comment by fabriciofx** [comment]
@dgroup And now, this PR seems to has a conflict. Could you check it too?

**Comment by dgroup** [comment]
@fabriciofx fixed, could you please review the PR again?

**Comment by fabriciofx** [comment]
@dgroup It's fine to me. @llorllale Could you merge it?

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#70](https://github.com/llorllale/cactoos-matchers/issues/70) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#70` doesn't exist in WBS, can't create order

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Pull request merged**
