### PR TITLE
(#68) Remove useless TeeInputHasResult

### PR DESCRIPTION
**Pull request by victornoel**
This is for #68.

Nothing specific there.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#104](https://github.com/llorllale/cactoos-matchers/issues/104) is now in scope, role is `REV`

**Comment by victornoel** [comment]
@llorllale this one is so simple I think you can review it yourself :)

**Comment by llorllale** [comment]
@rultor merge

**Comment by victornoel** [comment]
@llorllale I don't understand the error, it is about files that were not modified, is it because master is broken?

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#104` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#104](https://github.com/llorllale/cactoos-matchers/issues/104) is now out of scope

**Pull request merged**
