### PR TITLE
#60: Text matchers should describe actual/expected values separately

### PR DESCRIPTION
**Pull request by dgroup**
#60

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#61](https://github.com/llorllale/cactoos-matchers/issues/61) is now in scope, role is `REV`

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#61` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#61](https://github.com/llorllale/cactoos-matchers/issues/61) is now out of scope

**Pull request merged**
