### PR TITLE
(#175) Add windows-2019

### PR DESCRIPTION
**Pull request by baudoliver7**
For #175 :

- Add windows 2019 in workflow

### CODE REVIEW

**Comment by 0crat** [comment]
@baudoliver7[/z](https://www.0crat.com/u/baudoliver7) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @victornoel[/z](https://www.0crat.com/u/victornoel) please review this and merge or reject

**Comment by victornoel** [comment]
@baudoliver7 looks like it's working without code change, thanks ;)

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#238` is not assigned, can't get performer

**Pull request merged**
